import _ from "lodash";
import dayjs from "dayjs";
import { ObjectT } from "@/stores/modules/current";
import { Column } from "@/stores/modules/getStore";
import { FormatEnum } from "@/utils/models";

export interface Columns {
    [key: string]: Array<Column>;
}

export const columns: Columns = {
    user: [
        {
            title: "id",
            dataIndex: "id_user",
            key: "id_user",
            dataType: "string",
            showOnAdd: false,
            sorter: true,
            primary: true,
            editable: false,
        },
        {
            title: "Имя",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Фамилия",
            dataIndex: "surname",
            key: "surname",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Отчество",
            dataIndex: "patronymic",
            key: "patronymic",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Логин",
            dataIndex: "login",
            key: "login",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Пароль",
        //     dataIndex: "password",
        //     key: "password",
        //     showOnAdd: true,
        //     dataType: "string",
        //     sorter: true,
        //     editable: true,
        // },
        {
            title: "Забанен?",
            dataIndex: "banned",
            key: "banned",
            dataType: "boolean",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Роль",
            dataIndex: "user_role",
            key: "user_role",
            dataType: "enum",
            showOnAdd: true,
            enum: ["admin", "worker", "not_activated"],
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Действие",
            key: "action",
            dataType: "action",
        } as Column,
    ],

    jobtitle: [
        {
            title: "id",
            dataIndex: "id_job_title",
            key: "id_job_title",
            dataType: "string",
            showOnAdd: false,
            sorter: true,
            primary: true,
            editable: false,
        },
        {
            title: "Название",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showOnEntity: true,
        },
        {
            title: "Описание",
            dataIndex: "description",
            key: "description",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },

        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Действие",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    communication: [
        {
            title: "id",
            dataIndex: "id_communication",
            key: "id_communication",
            dataType: "string",
            showOnAdd: false,
            sorter: true,
            primary: true,
            editable: false,
        },
        {
            title: "Тип",
            dataIndex: "type",
            key: "type",
            dataType: "enum",
            enum: ["phone", "email"],
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Значение",
            dataIndex: "value",
            key: "value",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },

        {
            title: "Действие",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    accessuserscompany: [
        {
            title: "id",
            dataIndex: "id_access_users_company",
            key: "id_access_users_company",
            showOnAdd: false,
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
        },
        {
            title: "Админ",
            dataIndex: "fk_id_user",
            key: "fk_id_user",
            dataType: "fk",
            fkTableName: "user",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["login"],
        },
        {
            title: "Организация",
            dataIndex: "fk_id_company",
            key: "fk_id_company",
            dataType: "fk",
            fkTableName: "company",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    company: [
        {
            title: "id",
            dataIndex: "id_company",
            key: "id_company",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Имя",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Контактные данные",
            dataIndex: "contact",
            key: "contact",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Средство связи",
        //     dataIndex: "fk_id_communication",
        //     key: "fk_id_communication",
        //     dataType: "fk",
        //     fkTableName: "communication",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        //     showProps: ["type", "value"],
        // },
        /*        {
            title: 'address',
            dataIndex: 'address',
            key: 'address',
            dataType: 'string',
            showOnAdd: true,
            sorter: true,
            editable: true,
        }, */

        {
            title: "Форма",
            dataIndex: "format",
            key: "format",
            dataType: "enum",
            enum: Object.values(FormatEnum),
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "ИНН",
            dataIndex: "INN",
            key: "INN",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Префикс",
            dataIndex: "prefix",
            key: "prefix",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Email домен",
        //     dataIndex: "email_domain",
        //     key: "email_domain",
        //     dataType: "string",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        // },

        {
            title: "Описание",
            dataIndex: "description",
            key: "description",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Средство связи",
        //     dataIndex: "fk_id_communication",
        //     key: "fk_id_communication",
        //     dataType: "fk",
        //     fkTableName: "communication",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        //     showProps: ["type", "value"],
        // },
        {
            title: "AD домен",
            dataIndex: "fk_id_domain_ad",
            key: "fk_id_domain_ad",
            dataType: "fk",
            fkTableName: "domainad",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Контактный сотрудник",
            dataIndex: "fk_contact_wsuser",
            key: "fk_contact_wsuser",
            dataType: "fk",
            fkTableName: "wsuser",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["cn" /*, "name", "patronymic"*/],
        },
        {
            title: "Адрес",
            dataIndex: "fk_id_address",
            key: "fk_id_address",
            dataType: "fk",
            fkTableName: "address",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: [
                "zipCode",
                /*"country", "region", */ "city",
                "street",
                "house",
                "apartment",
            ],
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    address: [
        {
            title: "id",
            dataIndex: "idAddress",
            key: "idAddress",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Индекс",
            dataIndex: "zipCode",
            key: "zipCode",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Страна",
            dataIndex: "country",
            key: "country",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Область",
            dataIndex: "region",
            key: "region",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Город",
            dataIndex: "city",
            key: "city",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Улица",
            dataIndex: "street",
            key: "street",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дом",
            dataIndex: "house",
            key: "house",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Квартира",
            dataIndex: "apartment",
            key: "apartment",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],

    domainad: [
        {
            title: "id",
            dataIndex: "idDomainAd",
            key: "idDomainAd",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Синхронизация",
            dataIndex: "task",
            key: "task",
            dataType: "task",
            showOnAdd: false,
            sorter: false,
            editable: false,
        },

        {
            title: "Имя",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Адрес ldap",
            dataIndex: "url",
            key: "url",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Целевая ветка",
            dataIndex: "dn",
            key: "dn",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Ветка организации",
            dataIndex: "dnCompany",
            key: "dnCompany",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "ad login",
            dataIndex: "adlogin",
            key: "adlogin",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },

        {
            title: "Дата последнего обновления ад",
            dataIndex: "updateDate",
            key: "updateDate",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },

        {
            title: "ad password",
            dataIndex: "adpassword",
            key: "adpassword",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Примечание",
            dataIndex: "prim",
            key: "prim",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    domainmail: [
        {
            title: "id",
            dataIndex: "id_domain_mail",
            key: "id_domain_mail",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Организация",
            dataIndex: "fk_id_company",
            key: "fk_id_company",
            dataType: "fk",
            fkTableName: "company",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Имя домена",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    email: [
        {
            title: "id",
            dataIndex: "id_email",
            key: "id_email",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Email домен",
            dataIndex: "fk_id_domain_mail",
            key: "fk_id_domain_mail",
            dataType: "fk",
            fkTableName: "domainmail",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Адрес",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Адрес с доменом",
            dataIndex: "name_with_domain",
            key: "name_with_domain",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Пароль",
            dataIndex: "password",
            key: "password",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    officeequip: [
        {
            title: "id",
            dataIndex: "id_office_equip",
            key: "id_office_equip",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Организация",
            dataIndex: "fk_id_company",
            key: "fk_id_company",
            dataType: "fk",
            fkTableName: "company",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Тип оргтехники",
            dataIndex: "fk_id_office_equip_types",
            key: "fk_id_office_equip_types",
            dataType: "fk",
            fkTableName: "officeequiptypes",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Производитель",
            dataIndex: "fk_id_vendor",
            key: "fk_id_vendor",
            dataType: "fk",
            fkTableName: "vendor",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Название",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Описание",
            dataIndex: "description",
            key: "description",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Серийный номер",
            dataIndex: "serial",
            key: "serial",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Инвентарный номер",
            dataIndex: "inventoryNumber",
            key: "inventoryNumber",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дата ввода в э-л",
            dataIndex: "dateIn",
            key: "dateIn",
            dataType: "date",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дата вывода в э-л",
            dataIndex: "dateOut",
            key: "dateOut",
            dataType: "date",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Примечание",
            dataIndex: "prim",
            key: "prim",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Модель",
            dataIndex: "model",
            key: "model",
            dataType: "model",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    vendor: [
        {
            title: "id",
            dataIndex: "id_vendor",
            key: "id_vendor",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Тип",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Описание",
            dataIndex: "description",
            key: "description",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    officeequiptypes: [
        {
            title: "id",
            dataIndex: "id_office_equip_types",
            key: "id_office_equip_types",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Тип",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Описание",
            dataIndex: "description",
            key: "description",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    pass: [
        {
            title: "id",
            dataIndex: "id_pass",
            key: "id_pass",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Номер пропуска",
            dataIndex: "number",
            key: "number",
            dataType: "string",
            editable: true,
            showOnAdd: true,
            sorter: true,
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],

    wsuser: [
        {
            title: "id",
            dataIndex: "id_ws_user",
            key: "id_ws_user",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "Полное имя",
            dataIndex: "fullname",
            key: "fullname",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дата рождения",
            dataIndex: "dob ",
            key: "dob",
            dataType: "date",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        // {
        //     title: "Имя",
        //     dataIndex: "name",
        //     key: "name",
        //     dataType: "string",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        // },
        //
        // {
        //     title: "Отчество",
        //     dataIndex: "patronymic",
        //     key: "patronymic",
        //     dataType: "string",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        // },
        {
            title: "Примечание",
            dataIndex: "prim",
            key: "prim",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Должность",
            dataIndex: "fk_job_title",
            key: "fk_job_title",
            dataType: "fk",
            fkTableName: "jobtitle",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        {
            title: "Организация",
            dataIndex: "fk_id_company",
            key: "fk_id_company",
            dataType: "fk",
            fkTableName: "company",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
            // filters: [
            //     { text: "Male", value: "male" },
            //     { text: "Female", value: "female" },
            // ],
        },
        {
            title: "Оргтехника",
            dataIndex: "fk_office_equip",
            key: "fk_office_equip",
            dataType: "fk",
            fkTableName: "officeequip",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name"],
        },
        // {
        //     title: "ad user",
        //     dataIndex: "fk_ws_user",
        //     key: "fk_ws_user",
        //     dataType: "fk",
        //     fkTableName: "wsuser",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: true,
        //     showProps: ["cn"],
        // },
        {
            title: "Email",
            dataIndex: "fk_id_email",
            key: "fk_id_email",
            dataType: "fk",
            fkTableName: "email",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["name_with_domain"],
        },
        {
            title: "Средство связи",
            dataIndex: "fk_communication",
            key: "fk_communication",
            dataType: "fk",
            fkTableName: "communication",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["type", "value"],
        },
        {
            title: "Пропуск",
            dataIndex: "fk_pass",
            key: "fk_pass",
            dataType: "fk",
            fkTableName: "pass",
            showOnAdd: true,
            sorter: true,
            editable: true,
            showProps: ["number"],
        },
        {
            title: "objectGUID",
            dataIndex: "objectGUID",
            key: "objectGUID",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "cn",
            dataIndex: "cn",
            key: "cn",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "password",
            dataIndex: "password",
            key: "password",
            dataType: "string",
            editable: true,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "displayName",
            dataIndex: "displayName",
            key: "displayName",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "name",
            dataIndex: "name",
            key: "name",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "sn",
            dataIndex: "sn",
            key: "sn",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "userPrincipalName",
            dataIndex: "userPrincipalName",
            key: "userPrincipalName",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },

        {
            title: "objectClass",
            dataIndex: "objectClass",
            key: "objectClass",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "fk_id_ad_domain",
            dataIndex: "fk_id_ad_domain",
            key: "fk_id_ad_domain",
            dataType: "fk",
            fkTableName: "domainad",
            editable: false,
            showOnAdd: false,
            sorter: true,
            showProps: ["name"],
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
    wsgroup: [
        {
            title: "id",
            dataIndex: "id_ws_group",
            key: "id_ws_group",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "objectGUID",
            dataIndex: "objectGUID",
            key: "objectGUID",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "dn",
            dataIndex: "dn",
            key: "dn",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },
        {
            title: "cn",
            dataIndex: "cn",
            key: "cn",
            dataType: "string",
            editable: false,
            showOnAdd: false,
            sorter: true,
        },

        {
            title: "fk_id_ad_domain",
            dataIndex: "fk_id_ad_domain",
            key: "fk_id_ad_domain",
            dataType: "fk",
            fkTableName: "domainad",
            editable: false,
            showOnAdd: false,
            sorter: true,
            showProps: ["name"],
        },
        // {
        //     title: "Кто создал",
        //     dataIndex: "fk_who_create",
        //     key: "fk_who_create",
        //     dataType: "fk",
        //     fkTableName: "userCreate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        // {
        //     title: "Кто изменил",
        //     dataIndex: "fk_who_update",
        //     key: "fk_who_update",
        //     dataType: "fk",
        //     fkTableName: "userUpdate",
        //     showOnAdd: true,
        //     sorter: true,
        //     editable: false,
        //     showProps: ["login"],
        // },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],

    allowedip: [
        {
            title: "id_allowed_ip",
            dataIndex: "id_allowed_ip",
            key: "id_allowed_ip",
            dataType: "string",
            sorter: true,
            primary: true,
            editable: false,
            showOnAdd: false,
        },
        {
            title: "ip адрес",
            dataIndex: "address",
            key: "address",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Примечание",
            dataIndex: "prim",
            key: "prim",
            dataType: "string",
            showOnAdd: true,
            sorter: true,
            editable: true,
        },
        {
            title: "Дата создания",
            dataIndex: "createdAt",
            key: "createdAt",
            showOnAdd: false,
            dataType: "date",
            sorter: true,
            editable: false,
        },
        {
            title: "Дата обновления",
            dataIndex: "updatedAt",
            key: "updatedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "Дата удаления",
            dataIndex: "deletedAt",
            key: "deletedAt",
            dataType: "date",
            showOnAdd: false,
            sorter: true,
            editable: false,
        },
        {
            title: "action",
            key: "action",
            dataType: "action",
        } as Column,
    ],
};

export function getDataType(obj: ObjectT, modelName: string, prop: string) {
    try {
        const modelColumns = columns[modelName];
        const colDef = modelColumns.find((col) => col.dataIndex === prop);
        return colDef?.dataType;
    } catch (e) {}
}

export function delFk(obj: ObjectT, modelName: string) {
    const res: ObjectT = {};
    for (const prop in obj) {
        const dataType = getDataType(obj, modelName, prop);
        if (dataType && dataType !== "fk") {
            res[prop] = obj[prop];
        }
    }
    return res;
}

export function getPk(modelName: string) {
    try {
        const modelColumns = columns[modelName];
        const colDef = modelColumns.find((col) => col.primary);
        return colDef?.dataIndex;
    } catch (e) {
        // console.log(e);
    }
}

export interface Relation {
    title?: string;
    name: string;
    count: string;
    showOnAdd?: boolean;
    table?: string;
    fk?: string;
    tableName: string;
}

export interface Relations {
    [key: string]: Array<Relation>;
}

export const modelRelations: Relations = {
    user: [],
    jobtitle: [],
    person: [
        {
            title: "должность",
            tableName: "jobtitle",
            name: "jobtitle",
            count: "one",
            table: "person",
            fk: "fk_job_title",
            showOnAdd: true,
        },
    ],
    communication: [
        {
            title: "Пользователь",
            name: "wsuser",
            tableName: "wsuser",
            count: "one",
            showOnAdd: false,
        },
    ],
    address: [{ name: "company", tableName: "company", count: "one", showOnAdd: false }],
    company: [
        {
            title: "контактного сотрудника",
            tableName: "wsuser",
            name: "contactuser",
            count: "one",
            table: "company",
            fk: "fk_id_domain_ad",
            showOnAdd: true,
        },
        {
            title: "адрес",
            tableName: "address",
            name: "address",
            count: "one",
            table: "company",
            fk: "fk_id_address",
            showOnAdd: true,
        },
        {
            title: "AD домен",
            tableName: "domainad",
            name: "domainad",
            count: "one",
            table: "company",
            fk: "fk_id_domain_ad",
            showOnAdd: true,
        },
        {
            title: "email домен",
            tableName: "domainmail",
            name: "domainmail",
            count: "many",
            showOnAdd: true,
        },
        {
            title: "пользователя для организации",
            tableName: "wsuser",
            name: "wsuser",
            count: "many",
            showOnAdd: true,
        },
        {
            title: "оргтехнику",
            tableName: "officeequip",
            name: "officeequip",
            count: "many",
        },
    ],
    domainad: [
        {
            title: "организацию",
            name: "company",
            tableName: "company",
            count: "one",
            showOnAdd: false,
        },
    ],
    domainmail: [
        { title: "email", name: "email", tableName: "email", count: "many", showOnAdd: true },
    ],
    email: [
        {
            title: "email домен",
            name: "domainmail",
            tableName: "domainmail",
            count: "one",
            showOnAdd: false,
        },
    ],
    officeequip: [
        // { title: "организацию", name: "company", count: "one", showOnAdd: false },
        {
            title: "тип оргтехники",
            name: "officeequiptypes",
            tableName: "officeequiptypes",
            count: "one",
            showOnAdd: true,
        },
    ],
    officeequiptypes: [
        {
            title: "оргтехнику",
            name: "officeequip",
            tableName: "officeequip",
            count: "many",
            showOnAdd: false,
        },
    ],
    pass: [
        /* { title: "пользователя", name: "person", count: "one", showOnAdd: false } */
    ],
    wsgroup: [
        {
            title: "wsuser",
            name: "wsuser",
            tableName: "tableName",
            count: "many",
            showOnAdd: false,
        },
    ],
    wsuser: [
        { title: "wsgroup", name: "wsgroup", tableName: "wsgroup", count: "many", showOnAdd: true },
    ],
};

interface showedPropsT {
    [key: string]: string[];
}

const showedProps: showedPropsT = {
    jobtitle: ["name"],
    person: ["surname", "name", "patronymic"],
    // user2: ["surname", "name", "patronymic"],
    pass: ["number"],
    communication: ["type", "value"],
    email: ["name_with_domain"],
    officeequip: ["name"],
    company: ["name"],
    wsuser: ["cn", "fullname"],
};

export function getFkModels(modelName: string, payload: ObjectT) {
    try {
        // // console.log("getfkmodels");
        const relations = modelRelations[modelName];
        // // console.log(relations);
        return relations.filter((rel) => {
            if (rel.count === "one") {
                /* if(!payload) return false */
                if (payload[rel.name] !== null) return true;
            } else if (rel.count === "many") {
                if (payload && payload[rel.name] && payload[rel.name].length !== 0) return true;
            }
        });
    } catch (e) {
        // console.log(e);
    }
}

export function getColumnsByModelName(name: string) {
    return columns[name];
}

export function getShowOnEntityProperty(payload: ObjectT, model: string) {
    const shProps = showedProps[model];
    if (shProps) {
        let result = "";
        shProps.forEach((prop) => {
            const current = payload[prop];
            if (!_.isUndefined(current) && !_.isNull(current)) {
                result = `${result + payload[prop]} `;
            }
        });
        return result;
    }
    return model;
}

export function delTimeStamp(obj: ObjectT) {
    const res = _.cloneDeep(obj);
    delete res.createdAt;
    delete res.updatedAt;
    delete res.deletedAt;
    return res;
}

export function format(date: string) {
    if (!_.isUndefined(date) && !_.isNull(date)) {
        return dayjs(date).format("DD.MM.YYYY");
    }
    return "";
}

export function getFkDataForColumn(payload: ObjectT, route: string, column: Column) {
    //console.log("PAY__", payload);
    const fkTableName = column.fkTableName as string;
    const cols = column.showProps as string[];
    if (!fkTableName || !cols) {
        return payload[column.dataIndex];
    }
    if (column.fkTableName && _.has(payload, fkTableName) && !_.isNull(payload[fkTableName])) {
        const cols = column.showProps;
        const resultString = _.map(cols, (dataIndex) => {
            if (
                _.has(payload[fkTableName], dataIndex) &&
                !_.isNull(payload[fkTableName][dataIndex])
            ) {
                return payload[fkTableName][dataIndex];
            }
        })
            .filter((value) => !_.isUndefined(value))
            .join(" ");
        return resultString;
    }
}

export function getFkDataForEntity(
    value: null | number,
    prop: string,
    modelType: string,
    payload: ObjectT
) {
    //console.log("getFkDataForEntity__", value, prop, modelType);
    const col = columns[modelType].find((column) => column.dataIndex === prop) as Column;
    return getFkDataForColumn(payload, modelType, col);
}

export function getPropName(prop: string, modelType: string) {
    //console.log("getFkDataForEntity__", value, prop, modelType);
    const col = columns[modelType].find((column) => column.dataIndex === prop) as Column;
    if (!col) return false;
    return col.title;
}

export function getModelTypeForEntity2RouterLink(modelType: string, prop: string) {
    const col = columns[modelType].find((column) => column.dataIndex === prop) as Column;
    return col.fkTableName;
}
